# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jojo/Desktop/Elevator/elevator_project/elevator_project.cache/wt [current_project]
set_property parent.project_path C:/Users/jojo/Desktop/Elevator/elevator_project/elevator_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/jojo/Desktop/Elevator/Fsm.v
  C:/Users/jojo/Desktop/Elevator/StatusInputBuffer.v
  C:/Users/jojo/Desktop/Elevator/StatusTransition.v
}
read_xdc C:/Users/jojo/Desktop/Elevator/DDR_nexys4.xdc
set_property used_in_implementation false [get_files C:/Users/jojo/Desktop/Elevator/DDR_nexys4.xdc]

synth_design -top StatusTransition -part xc7a100tcsg324-1
write_checkpoint -noxdef StatusTransition.dcp
catch { report_utilization -file StatusTransition_utilization_synth.rpt -pb StatusTransition_utilization_synth.pb }
